---
heat_template_version: 2015-10-15
description: A template to deploy the Kubernetes cluster
parameters:
  image:
    type: string
    description: Image used for servers
  flavor:
    type: string
    description: Flavor used by the servers
  security_group_name:
    type: string
    description: Security group used by the servers
  private_net:
    type: string
    description: Network used by the servers
  public_net:
    type: string
    description: Public IP used by the servers
  ansible_repo:
    type: string
    description: "Kubernetes ansible playbook repo"
    default: "https://github.com/kairen/heat-k8s-template.git"

resources:
  prefix:
    type: OS::Heat::TestResource
    properties:
      value: { get_param: "OS::stack_name" }

  keypair:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name:
        str_replace:
          template: "%prefix%-keypair"
          params:
            "%prefix%": { get_attr: [prefix, output] }

  k8s_master_node:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "%prefix%-master"
          params:
            "%prefix%": { get_attr: [prefix, output] }
      image: { get_param: image }
      key_name: { get_resource: keypair }
      flavor: { get_param: flavor }
      networks:
      - network: { get_param: private_net }
      security_groups:
      - get_param: security_group_name

  k8s_worker_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server
        properties:
          name:
            str_replace:
              template: "%prefix%-worker-%index%"
              params:
                "%prefix%": { get_attr: [prefix, output] }
          image: { get_param: image }
          key_name: { get_resource: keypair }
          flavor: { get_param: flavor }
          networks:
          - network: { get_param: private_net }
          security_groups:
          - get_param: security_group_name

  swift_signal_handle:
    type: OS::Heat::SwiftSignalHandle

  swift_signal:
    type: OS::Heat::SwiftSignal
    properties:
      handle: { get_resource: swift_signal_handle }
      count: 1
      timeout: 14400

  cloud_config_ansible:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
          - path: "/opt/k8s/id_rsa"
            permissions: "0600"
            content: { get_attr: [keypair, private_key] }
          - path: "/opt/k8s/hosts.j2"
            permissions: "0600"
            content: |
              [all]
              master ansible_ssh_host={{ master_node_ip_address }}
              {% for worker_node_ip_address in worker_nodes_ip_address %}
              worker-{{ loop.index0 }} ansible_ssh_host={{ worker_node_ip_address }}
              {% endfor %}

              [masters]
              master

              [nodes]
              {% for worker_node_ip_address in worker_nodes_ip_address %}
              worker-{{ loop.index0 }}
              {% endfor %}
          - path: "/opt/k8s/environment.yaml"
            permissions: "0600"
            content:
              str_replace:
                template: |
                  ---
                  master_node_ip_address: "%master_node_ip_address%"
                  master_node_floating_ip: "%master_node_floating_ip%"
                  worker_nodes_ip_address: %worker_nodes_ip_address%
                params:
                  "%master_node_ip_address%": { get_attr: [k8s_master_node, first_address] }
                  "%master_node_floating_ip%": { get_attr: [floating_ip, floating_ip_address] }
                  "%worker_nodes_ip_address%": { get_attr: [k8s_worker_nodes, first_address] }
          - path: "/opt/k8s/runcmd-bash"
            permissions: "0700"
            content:
              str_replace:
                template: |
                  #!/bin/bash

                  function exit_failure {
                    %swift_signal_notify% --data-binary '{"status": "FAILURE", "reason": "'"$@"'"}'
                    exit 1
                  }

                  function exit_success {
                    %swift_signal_notify% --data-binary '{"status": "SUCCESS"}'
                  }

                  sudo apt-add-repository -y ppa:ansible/ansible || exit_failure "Ansible key added apt"
                  sudo apt-get update && sudo apt-get install -y ansible || exit_failure "Ansible apt install"

                  git clone %ansible_repo% /opt/k8s/heat-k8s-template || exit_failure "Git Clone - %ansible_repo%"
                  cd /opt/k8s/heat-k8s-template/ansible

                  ansible localhost -e @/opt/k8s/environment.yaml \
                    -m template \
                    -a "src=/opt/k8s/hosts.j2 \
                    dest=/opt/k8s/hosts.ini" || exit_failure "Ansible Inventory Template"

                  # Run ansible playbook to install kubernetes
                  ansible-playbook playbook.yaml -vv || exit_failure "Ansible Playbook Run"

                  exit_success
                params:
                  "%swift_signal_notify%": { get_attr: [swift_signal_handle, curl_cli] }
        runcmd:
          - ./opt/k8s/runcmd-bash

  kube_ansible_deploy:
    depends_on:
      - k8s_master_node
      - k8s_worker_nodes
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "%prefix%-ansible"
          params:
            "%prefix%": { get_attr: [prefix, output] }
      image: { get_param: image }
      key_name: { get_resource: keypair }
      flavor: { get_param: flavor }
      networks:
      - network: { get_param: private_net }
      security_groups:
      - get_param: security_group_name
      user_data_format: RAW
      user_data: { get_resource: cloud_config_ansible }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }

  floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: k8s_master_node }

outputs:
  master_ip:
    description: IP address of master
    value: { get_attr: [k8s_master_node, first_address] }
  workers_ip:
    description: IP address of workers
    value: { get_attr: [k8s_worker_nodes, first_address] }
  floating_ip:
    description: Floating IP of master
    value: { get_attr: [floating_ip, floating_ip_address] }
  private_key:
    description: Private key of all nodes
    value: { get_attr: [keypair, private_key] }
